
spring:
  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

  h2:
    console:
      enabled: true
  batch:
    jdbc:
      schema:
  messages:
    basename: errors

logging:
  level:
#    org.hibernate.SQL: debug
    com.kmini.store: info
#    com.zaxxer.hikari: TRACE
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    org.hibernate.type.descriptor.sql: trace
#    org.hibernate.type: trace

file:
  dir:
    C:/Users/kmin/images/